config/routes.rb
Rails.application.routes.draw do
  resources :autors
root :to => "welcome#index"

  #root  "libros#index"
  devise_for :users
  get 'users.json', to: 'user#index', as: 'users'
  resources :libros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: [:show, :edit, :update, :destroy]

  # GET /autors
  # GET /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1
  # GET /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors
  # POST /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: 'Autor was successfully created.' }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1
  # PATCH/PUT /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: 'Autor was successfully updated.' }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.json
  def destroy
    @autor.destroy
    respond_to do |format|
      format.html { redirect_to autors_url, notice: 'Autor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autor_params
      params.require(:autor).permit(:nombre, :libro, :edad)
    end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_libro, only: [:show, :edit, :update, :destroy]


  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:nombre, :edicion, :autor, :editorial)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    respond_to :json
    # POST /resource
    


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

    # POST /resource/sign_in

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
      @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/autors/_form.html.erb
<%= form_with(model: autor, local: true) do |form| %>
  <% if autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
      <% autor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :autor_nombre %>
  </div>

  <div class="field">
    <%= form.label :libro %>
    <%= form.text_field :libro, id: :autor_libro %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad, id: :autor_edad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Show', @autor %> |
<%= link_to 'Back', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Libro</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.nombre %></td>
        <td><%= autor.libro %></td>
        <td><%= autor.edad %></td>
        <td><%= link_to 'Show', autor %></td>
        <td><%= link_to 'Edit', edit_autor_path(autor) %></td>
        <td><%= link_to 'Destroy', autor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Autor', new_autor_path %>

app/views/autors/new.html.erb
<h1>New Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Back', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @autor.nombre %>
</p>

<p>
  <strong>Libro:</strong>
  <%= @autor.libro %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @autor.edad %>
</p>

<%= link_to 'Edit', edit_autor_path(@autor) %> |
<%= link_to 'Back', autors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  </head>

  <body>

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link ' %> |
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<% else %>
 
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>

app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :libro_nombre %>
  </div>

  <div class="field">
    <%= form.label :edicion %>
    <%= form.text_field :edicion, id: :libro_edicion %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor, id: :libro_autor %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.text_field :editorial, id: :libro_editorial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edicion</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.nombre %></td>
        <td><%= libro.edicion %></td>
        <td><%= libro.autor %></td>
        <td><%= libro.editorial %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @libro.nombre %>
</p>

<p>
  <strong>Edicion:</strong>
  <%= @libro.edicion %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.autor %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @libro.editorial %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>

app/views/welcome/index.html.erb
<h1>Pagina Pricipal</h1>



<a href="libros.json">Libros</a>
<a href="autors.json">Autores</a>
<a href="users.json">Usuarios</a>